language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t jinia/docker-react-app-new .
script:
  - docker run -e CI=true jinia/docker-react-app-new npm run test
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-app-react"
  env: "DockerAppReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-178906624133"
  bucket_path: "docker-app-react"
on:
  branch: master
access_key_id: "$AWS_ACCESS_KEY"
secret_access_key:
  secure: "$AWS_SECRET_KEY"